GENERAL:
  BLACKLISTED_WORLDS_OPEN_PACK:
    - "ExampleWorld"
  BLACKLISTED_WORLDS_BLOCK_PLACEMENT:
    - "ExampleWorld"
  BLACKLISTED_WORLDS_PICKUP_ITEMS:
    - "ExampleWorld"
TEXTS_NOT_YET_IMPLEMENTED:
  MESSAGES:
    COMMANDS:
      MESSAGE_COMMAND_SUBCOMMAND: "Please select a valid sub command"
      MESSAGE_COMMAND_SELECT_ITEM: "Please select an item type"
      MESSAGE_COMMAND_PACK_NO_EXIST: "Yeah, packs only go from 1 to 9 dummy :)"
      MESSAGE_COMMAND_DANK_PACK_GIVEN:
      MESSAGE_COMMAND_TRASH_PACK_GIVEN:
      MESSAGE_COMMAND_PACK_UPDATED:
    EVENTS:
      MESSAGE_EVENT_OPEN_DANK_PACK:
      MESSAGE_EVENT_OPEN_TRASH_PACK:
      MESSAGE_EVENT_INPUT_EXISTING:
      MESSAGE_EVENT_INPUT_THIS_DANK:
      MESSAGE_EVENT_WITHDRAW_NO_SPACE:
      MESSAGE_EVENT_SLOT_NOT_ASSIGNED:
      MESSAGE_EVENT_SLOT_CANT_PLACE:
      MESSAGE_EVENT_SLOT_NO_MORE_ITEMS:
      MESSAGE_EVENT_SLOT_CHANGED:
    CRAFTING:
      MESSAGE_CRAFT_NEW_PACK:
      MESSAGE_CRAFT_UPGRADE_PACK:
      MESSAGE_CRAFT_NEW_TRASH:
      MESSAGE_CRAFT_UPGRADE_TRASH: