auto-update: false
GENERAL:
  DEBUG: true
  BLACKLISTED_WORLDS_OPEN_PACK:
    - "ExampleWorld"
  BLACKLISTED_WORLDS_BLOCK_PLACEMENT:
    - "ExampleWorld"
  BLACKLISTED_WORLDS_PICKUP_ITEMS:
    - "ExampleWorld"
  TOGGLES:
    ENABLE_RANGE_UPGRADE: true
    ENABLE_SMELTING_UPGRADE: true
    ENABLE_AUTO_SELL_UPGRADE: true # Also requires a supported shop plugin
VALUES:
  AMOUNT_PER_SLOT_T1: 256
  AMOUNT_PER_SLOT_T2: 1024
  AMOUNT_PER_SLOT_T3: 2048
  AMOUNT_PER_SLOT_T4: 4096
  AMOUNT_PER_SLOT_T5: 8192
  AMOUNT_PER_SLOT_T6: 16384
  AMOUNT_PER_SLOT_T7: 65536
  AMOUNT_PER_SLOT_T8: 524288
  AMOUNT_PER_SLOT_T9: 2147483547 # DO NOT GO ABOVE 2147483547
TEXTS:
  GUI:
    FILLER: "获得水球!"
    INFO_NAME: "水球信息"
    INFO_LORE_ID: "水球ID"
    INFO_LORE_LEVEL: "水球等级"
    LOCKED_SLOT: "锁定槽位"
    UNASSIGNED_SLOT: "空槽位"
    UNASSIGNED_SLOT_LORE:
      - "空槽位, 请在下面放置一个"
      - "与该槽位类型匹配的物品"
    INTERACT_DANK_PACK_BUTTON_NAME: "取出 / 增加物品"
    INTERACT_TRASH_PACK_BUTTON_NAME: "移除物品"
    INTERACT_LEFT_CLICK_NAME: "L左键"
    INTERACT_LEFT_CLICK_PACK_ACTION: "取出一个"
    INTERACT_LEFT_CLICK_TRASH_ACTION: "重置槽位"
    INTERACT_RIGHT_CLICK_NAME: "右键"
    INTERACT_RIGHT_CLICK_ACTION: "取出一组"
    INTERACT_SHIFT_LEFT_CLICK_NAME: "Shift 左键"
    INTERACT_SHIFT_LEFT_CLICK_ACTION: "将整个背包物品放入"
    INTERACT_SHIFT_RIGHT_CLICK_NAME: "Shift 右键"
    INTERACT_SHIFT_RIGHT_CLICK_ACTION: "填满背包"
    INTERACT_DROP_CLICK_NAME: "丢弃 (Q)"
    INTERACT_DROP_CLICK_ACTION: "丢弃一组"
  ITEM_DETAILS:
    ITEM_DANK_PACK: "水球存储槽"
    ITEM_DANK_PACK_LORE:
      - "A dimension folded into a single point of"
      - "space and time. All this just to hold"
      - "your trash!"
    ITEM_DANK_PACK_VOID_INFO: "Items over limit are voided"
    ITEM_DANK_TRASH: "Dank Trash Pack"
    ITEM_TRASH_PACK_LORE:
      - "A dimension folded into a single point of"
      - "space and time. All this just to hold"
      - "your trash!"
    ITEM_DANK_TRASH_VOID_INFO: "All matching items will be voided"
    ITEM_SLOT_NUMBER: "Slots"
    ITEM_SLOT_AMOUNT_PER: "Amount per slot"
    ITEM_RIGHT_CLICK: "Right click to open pack"
    ITEM_STORAGE_CELL: "Storage Cell"
    ITEM_UPGRADE_RANGE: "Dank Vacuum Upgrade"
    ITEM_UPGRADE_SMELTING: "Dank Smelting Upgrade"
    ITEM_UPGRADE_AUTO_SELL: "Dank Merchant Upgrade"
    ITEM_UPGRADE_STACKING_INFO: "Stacks up to"
  MESSAGES:
    COMMANDS:
      COMMAND_SUBCOMMAND: "Please select a valid sub command"
      COMMAND_SELECT_ITEM: "Please select an item type"
      COMMAND_PACK_NO_EXIST: "Yeah, packs only go from 1 to 9 dummy :)"
      COMMAND_DANK_PACK_GIVEN: "Dank Pack created."
      COMMAND_TRASH_PACK_GIVEN: "Trash Pack created."
      COMMAND_PACK_UPDATED: "This pack is old or incorrectly made, updating to newest format."
      COMMAND_BLACKLIST_ITEM_SAVED: "Held item added to Dank Blacklist, existing items will not be removed."
      COMMAND_BLACKLIST_ITEM_MUST_HOLD: "You must be holding the item you want added to the blacklist."
    CRAFTING:
      CRAFT_NEW_PACK: "You have crafted a new Dank Pack"
      CRAFT_UPGRADE_PACK: "You have upgraded a Dank Pack"
      CRAFT_NEW_TRASH: "You have crafted a new Dank Trash Can"
      CRAFT_UPGRADE_TRASH: "You have upgraded a Dank Trash Can"
    EVENTS:
      EVENT_OPEN_DANK_PACK: "Opening Dank Pack"
      EVENT_OPEN_TRASH_PACK: "Opening Dank Trash"
      EVENT_INPUT_EXISTING: "Slot is already assigned."
      EVENT_INPUT_THIS_DANK: "You cannot put a Dank inside itself silly!"
      EVENT_INPUT_BLACKLISTED: "This item cannot go into a dank as it has been blacklisted."
      EVENT_WITHDRAW_NO_SPACE: "You need an empty inventory slot."
      EVENT_SLOT_NOT_ASSIGNED: "No item registered"
      EVENT_SLOT_CANT_PLACE: "The selected item can't be placed via a Dank"
      EVENT_SLOT_NO_MORE_ITEMS: "The selected item has run out!"
      EVENT_SLOT_CHANGED: "Selected Slot"
