name: DankTech
version: 1.2.1
main: io.github.sefiraat.danktech.DankTech
api-version: 1.16
softdepend:
  - GriefPrevention
  - WorldGuard
  - mcMMO
  - Slimefun
permissions:
  danktech.admin:
    description: Allows access to /danktech and to bypass world restrictions